/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Resposta } from './resposta';
import { Usuario } from './usuario';
import { AvaliacaoResolucaoListaDTO } from './avaliacaoResolucaoListaDTO';


export interface AvaliacaoRespostaDTO { 
    id?: number;
    avaliacaoResolucaoLista?: AvaliacaoResolucaoListaDTO;
    respostaId?: string;
    avaliadorId?: string;
    comentario?: string;
    nota?: number;
    publicada?: boolean;
    dataCadastro?: Date;
    dataAlteracao?: Date;
    resposta?: Resposta;
    avaliador?: Usuario;
}

