/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Usuario } from './usuario';
import { AplicacaoLista } from './aplicacaoLista';


export interface AvaliacaoLista {
  id?: number;
  aplicacaoLista: AplicacaoLista;
  avaliadores?: Array<Usuario>;
  criterioAvaliacao: AvaliacaoLista.CriterioAvaliacaoEnum;
  dataCadastro?: Date;
  usuarioCadastro?: string;
  dataAlteracao?: Date;
  usuarioAlteracao?: string;
}

export namespace AvaliacaoLista {
  export type CriterioAvaliacaoEnum = 'MESA_REDONDA' | 'FIFO' | 'RANDOMICO';
  export const CriterioAvaliacaoEnum = {
    MESAREDONDA: 'MESA_REDONDA' as CriterioAvaliacaoEnum,
    FIFO: 'FIFO' as CriterioAvaliacaoEnum,
    RANDOMICO: 'RANDOMICO' as CriterioAvaliacaoEnum,
  };
}


