/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Resposta } from './resposta';
import { Usuario } from './usuario';
import { AvaliacaoResolucaoLista } from './avaliacaoResolucaoLista';


export interface AvaliacaoResposta {
  id?: number;
  avaliacaoResolucaoLista: AvaliacaoResolucaoLista;
  resposta: Resposta;
  avaliador: Usuario;
  comentario?: string;
  nota?: number;
  publicada: boolean;
  dataCadastro?: Date;
  dataAlteracao?: Date;
}

