###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "professor@ufg.br",
  "senha": "123456"
}

###
GET http://localhost:8080/api/resolucoes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyRGV0YWlscyI6IntcImR0eXBlXCI6XCJEb2NlbnRlXCIsXCJpZFwiOlwiNWQ5ZjYzMDk2NzQxZTYzOTFjMzM2YWZhXCIsXCJub21lXCI6XCJwcm9mZXNzb3JAdWZnLmJyXCIsXCJlbWFpbFwiOlwicHJvZmVzc29yQHVmZy5iclwiLFwic2VuaGFcIjpudWxsLFwiYXV0aG9yaXRpZXNcIjpbXCJqYXZhLnV0aWwuQXJyYXlMaXN0XCIsW3tcIkBjbGFzc1wiOlwib3JnLnNwcmluZ2ZyYW1ld29yay5zZWN1cml0eS5jb3JlLmF1dGhvcml0eS5TaW1wbGVHcmFudGVkQXV0aG9yaXR5XCIsXCJhdXRob3JpdHlcIjpcIlJPTEVfRE9DRU5URVwifV1dLFwicGFzc3dvcmRcIjpudWxsLFwidXNlcm5hbWVcIjpcInByb2Zlc3NvckB1ZmcuYnJcIixcImFjY291bnROb25FeHBpcmVkXCI6dHJ1ZSxcImFjY291bnROb25Mb2NrZWRcIjp0cnVlLFwiY3JlZGVudGlhbHNOb25FeHBpcmVkXCI6dHJ1ZSxcImVuYWJsZWRcIjp0cnVlfSJ9.x9p7f4M9slaRzHYGy2xfd2rMkMZ15v9L4CpyTvtTd8Q

### Cria avaliaçao para uma resoluçao
POST http://localhost:8080/api/avaliacoesResolucao
Content-Type: application/json

{
  "resolucaoLista": {
    "id": "b256f986-14a5-4f90-a6b7-a0b96d87ab52"
  },
  "avaliador": {
    "dtype": "Discente",
    "id": "585c69cd-c9e1-46f3-9135-cf1939cf5d48"
  }
}

###
GET http://localhost:8080/api/avaliacoesResolucao/1

### Atribui nota para uma avaliaçao
PUT http://localhost:8080/api/avaliacoesResolucao/1
Content-Type: application/json

{
  "resolucaoLista": {
    "id": "eda11d18-ba3f-44c2-a375-0ed475a5957b"
  },
  "avaliador": {
    "dtype": "Discente",
    "id": "585c69cd-c9e1-46f3-9135-cf1939cf5d48"
  },
  "nota": 5.0
}

### Cria avaliaçao para uma resoluçao
POST http://localhost:8080/api/avaliacoesResposta
Content-Type: application/json

{
  "resposta": {
    "id": "bed12160-bc58-4501-a93c-4ce258f779c8"
  },
  "avaliador": {
    "dtype": "Discente",
    "id": "585c69cd-c9e1-46f3-9135-cf1939cf5d48"
  },
  "avaliacaoResolucaoLista": {
    "id": 1
  }
}

###
