export * from './avaliacoes.service';
import { AvaliacoesService } from './avaliacoes.service';
export * from './avaliacoesResolucao.service';
import { AvaliacoesResolucaoService } from './avaliacoesResolucao.service';
export * from './avaliacoesResposta.service';
import { AvaliacoesRespostaService } from './avaliacoesResposta.service';
export * from './distribua.service';
import { DistribuaService } from './distribua.service';
export * from './id.service';
import { IdService } from './id.service';
export * from './minhas.service';
import { MinhasService } from './minhas.service';
export * from './paraAvaliar.service';
import { ParaAvaliarService } from './paraAvaliar.service';
export * from './resolucoes.service';
import { ResolucoesService } from './resolucoes.service';
export * from './respostaId.service';
import { RespostaIdService } from './respostaId.service';
export * from './respostas.service';
import { RespostasService } from './respostas.service';
export const APIS = [AvaliacoesService, AvaliacoesResolucaoService, AvaliacoesRespostaService, DistribuaService, IdService, MinhasService, ParaAvaliarService, ResolucoesService, RespostaIdService, RespostasService];
