export * from './apiAvaliacoes.service';
import { ApiAvaliacoesService } from './apiAvaliacoes.service';
export * from './apiAvaliacoesId.service';
import { ApiAvaliacoesIdService } from './apiAvaliacoesId.service';
export * from './apiAvaliacoesIdDistribua.service';
import { ApiAvaliacoesIdDistribuaService } from './apiAvaliacoesIdDistribua.service';
export * from './apiAvaliacoesResolucao.service';
import { ApiAvaliacoesResolucaoService } from './apiAvaliacoesResolucao.service';
export * from './apiAvaliacoesResolucaoAvaliacaoResolucaoListaIdRespostaId.service';
import { ApiAvaliacoesResolucaoAvaliacaoResolucaoListaIdRespostaIdService } from './apiAvaliacoesResolucaoAvaliacaoResolucaoListaIdRespostaId.service';
export * from './apiAvaliacoesResolucaoAvaliacaoResolucaoListaIdRespostas.service';
import { ApiAvaliacoesResolucaoAvaliacaoResolucaoListaIdRespostasService } from './apiAvaliacoesResolucaoAvaliacaoResolucaoListaIdRespostas.service';
export * from './apiAvaliacoesResolucaoId.service';
import { ApiAvaliacoesResolucaoIdService } from './apiAvaliacoesResolucaoId.service';
export * from './apiAvaliacoesResolucaoMinhas.service';
import { ApiAvaliacoesResolucaoMinhasService } from './apiAvaliacoesResolucaoMinhas.service';
export * from './apiAvaliacoesResolucaoParaAvaliar.service';
import { ApiAvaliacoesResolucaoParaAvaliarService } from './apiAvaliacoesResolucaoParaAvaliar.service';
export * from './apiAvaliacoesResposta.service';
import { ApiAvaliacoesRespostaService } from './apiAvaliacoesResposta.service';
export * from './apiAvaliacoesRespostaId.service';
import { ApiAvaliacoesRespostaIdService } from './apiAvaliacoesRespostaId.service';
export * from './apiResolucoes.service';
import { ApiResolucoesService } from './apiResolucoes.service';
export * from './apiResolucoesId.service';
import { ApiResolucoesIdService } from './apiResolucoesId.service';
export * from './apiResolucoesResolucaoIdRespostas.service';
import { ApiResolucoesResolucaoIdRespostasService } from './apiResolucoesResolucaoIdRespostas.service';
export * from './apiRespostas.service';
import { ApiRespostasService } from './apiRespostas.service';
export * from './apiRespostasId.service';
import { ApiRespostasIdService } from './apiRespostasId.service';
export const APIS = [ApiAvaliacoesService, ApiAvaliacoesIdService, ApiAvaliacoesIdDistribuaService, ApiAvaliacoesResolucaoService, ApiAvaliacoesResolucaoAvaliacaoResolucaoListaIdRespostaIdService, ApiAvaliacoesResolucaoAvaliacaoResolucaoListaIdRespostasService, ApiAvaliacoesResolucaoIdService, ApiAvaliacoesResolucaoMinhasService, ApiAvaliacoesResolucaoParaAvaliarService, ApiAvaliacoesRespostaService, ApiAvaliacoesRespostaIdService, ApiResolucoesService, ApiResolucoesIdService, ApiResolucoesResolucaoIdRespostasService, ApiRespostasService, ApiRespostasIdService];
